# Generated by Django 6.0.6 on 2026-06-12 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Wash & Fold', 'Wash & Fold'), ('Wash & Iron', 'Wash & Iron'), ('Dry Cleaning', 'Dry Cleaning')], max_length=50)),
                ('pickup_address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending Pickup', 'Pending Pickup'), ('Picked Up', 'Picked Up'), ('Cleaning', 'Cleaning'), ('Ready', 'Ready'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], default='Pending Pickup', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
