# Generated by Django 6.0.6 on 2026-06-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Everyday Wear', 'Everyday Wear'), ('Traditional Wear', 'Traditional Wear'), ('Underwear', 'Underwear'), ('Bedding', 'Bedding'), ('Special Care', 'Special Care')], max_length=50)),
                ('service_type', models.CharField(choices=[('Wash & Fold', 'Wash & Fold'), ('Wash & Iron', 'Wash & Iron'), ('Dry Cleaning', 'Dry Cleaning')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='payment_method',
            field=models.CharField(choices=[('Pay Online', 'Pay Online'), ('Pay On Delivery', 'Pay On Delivery')], default='Pay On Delivery', max_length=30),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='pickup_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.laundryorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pricelist')),
            ],
        ),
    ]
