# Generated by Django 6.0.6 on 2026-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricelist_laundryorder_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='category',
            field=models.CharField(choices=[('Everyday Wear', 'Everyday Wear'), ('Corporate Wear', 'Corporate Wear'), ('Traditional Wear', 'Traditional Wear'), ('Underwear', 'Underwear'), ("Children's Wear", "Children's Wear"), ('Bedding', 'Bedding'), ('Special Care', 'Special Care')], max_length=50),
        ),
    ]
