# Generated by Django 6.0.6 on 2026-06-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pricelist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
