# Generated by Django 6.0.6 on 2026-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_laundryorder_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='pickup_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
