# Generated by Django 6.0.6 on 2026-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_laundryorder_delivery_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
