# Generated by Django 6.0.6 on 2026-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_laundryorder_transport_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
