# Generated by Django 6.0.6 on 2026-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_laundryorder_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('Pending Pickup', 'Pending Pickup'), ('Picked Up', 'Picked Up'), ('Cleaning', 'Cleaning'), ('Ready', 'Ready'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='Pending Pickup', max_length=30),
        ),
    ]
