# Generated by Django 6.0.6 on 2026-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_laundryorder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='laundryorder',
            name='status',
            field=models.CharField(choices=[('Pending Pickup', 'Pending Pickup'), ('Picked Up', 'Picked Up'), ('Cleaning', 'Cleaning'), ('Ready', 'Ready'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending Pickup', max_length=30),
        ),
    ]
