# Generated by Django 6.0.6 on 2026-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
