# Generated by Django 6.0.6 on 2026-06-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryorder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
