# Generated by Django 6.0.6 on 2026-06-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_laundryorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
