# Generated by Django 6.0.6 on 2026-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_laundryorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
