# Generated by Django 6.0.6 on 2026-06-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_laundryorder_pickup_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='delivery_verified',
            field=models.BooleanField(default=False),
        ),
    ]
