# Generated by Django 6.0.6 on 2026-06-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_laundryorder_delivery_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='delete_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='delete_pin_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
