# Generated by Django 6.0.6 on 2026-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_laundryorder_delete_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='WashEasy', max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('transport_price_per_km', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_sound', models.BooleanField(default=True)),
            ],
        ),
    ]
