# Generated by Django 6.0.6 on 2026-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='is_admin_seen',
            field=models.BooleanField(default=False),
        ),
    ]
