# Generated by Django 6.0.6 on 2026-06-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryorder',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='laundryorder',
            name='complaint_status',
        ),
    ]
