# Generated by Django 6.0.6 on 2026-06-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_laundryorder_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_admin_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='complaint_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
