# Generated by Django 6.0.6 on 2026-06-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_laundryorder_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='is_read',
            new_name='is_admin_seen',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
