# Generated by Django 6.0.6 on 2026-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_is_read_contactmessage_is_admin_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_address',
            field=models.CharField(default='199, Odunsi Street, Bariga, Lagos', max_length=255),
        ),
    ]
