# Generated by Django 6.0.6 on 2026-07-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sitesettings_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_latitude',
            field=models.FloatField(default=6.53699),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_longitude',
            field=models.FloatField(default=3.3963),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='business_address',
            field=models.CharField(default='119, Odunsi Street, Bariga, Lagos', max_length=255),
        ),
    ]
