# Generated by Django 6.0.6 on 2026-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sitesettings_business_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='customer_order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
