# Generated by Django 6.0.6 on 2026-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_laundryorder_customer_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryorder',
            name='payment_method',
            field=models.CharField(choices=[('Pay On Delivery', 'Pay On Delivery')], default='Pay On Delivery', max_length=30),
        ),
    ]
