# Generated by Django 6.0.6 on 2026-07-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_laundryorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='express_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='express_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge per item for Express Service', max_digits=10),
        ),
    ]
