# Generated by Django 6.0.6 on 2026-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pricelist_express_available_pricelist_express_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='express_service',
            field=models.BooleanField(default=False),
        ),
    ]
