# Generated by Django 6.0.6 on 2026-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_laundryorder_express_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='express_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
