# Generated by Django 6.0.6 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_orderitem_express_fee_orderitem_express_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
