# Generated by Django 6.0.6 on 2026-07-23 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_subscriptioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customersubscription'),
        ),
    ]
