# Generated by Django 6.0.6 on 2026-07-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_customersubscription_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.customersubscription'),
        ),
    ]
