# Generated by Django 6.0.6 on 2026-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_complaint_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
