# Generated by Django 6.0.6 on 2026-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_complaint_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='basic_subscription',
            field=models.BooleanField(default=False, verbose_name='Basic Subscription'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='premium_subscription',
            field=models.BooleanField(default=False, verbose_name='Premium Subscription'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='standard_subscription',
            field=models.BooleanField(default=False, verbose_name='Standard Subscription'),
        ),
    ]
