# Generated by Django 6.0.6 on 2026-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_pricelist_basic_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryorder',
            name='use_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
