# Generated by Django 6.0.6 on 2026-07-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_laundryorder_use_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='covered_by_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
