# Generated by Django 6.0.6 on 2026-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_orderitem_covered_by_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='free_transport_used',
            field=models.BooleanField(default=False),
        ),
    ]
