# Generated by Django 6.0.6 on 2026-07-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_customersubscription_free_transport_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='free_transport_used',
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='free_transport_trips_remaining',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
