# Generated by Django 6.0.6 on 2026-07-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_customersubscription_free_transport_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='free_transport_trips',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
