# Generated by Django 6.0.6 on 2026-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_subscriptionplan_free_transport_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
