# Generated by Django 6.0.6 on 2026-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_customersubscription_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Higher number means a higher subscription tier.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='upgrade_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
