# Generated by Django 6.0.6 on 2026-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_subscriptionplan_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_percentage', models.PositiveIntegerField(default=30, help_text='Maximum percentage of subscription duration allowed for upgrades.')),
                ('max_items_percentage', models.PositiveIntegerField(default=30, help_text='Maximum percentage of subscription items allowed for upgrades.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
