# Generated by Django 6.0.6 on 2026-07-26 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_upgradesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='previous_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_subscriptions', to='core.customersubscription'),
        ),
    ]
