# Generated by Django 6.0.6 on 2026-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_customersubscription_previous_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='remaining_items',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
