# Generated by Django 6.0.6 on 2026-08-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_subscriptionusage_options_and_more'),
        ('rewards', '0010_rewardprize_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='covered_by_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='rewards.customerreward'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reward_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of items covered by reward.'),
        ),
    ]
