# Generated by Django 6.0.6 on 2026-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_orderitem_covered_by_reward_orderitem_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity paid normally.'),
        ),
    ]
