# Generated by Django 6.0.6 on 2026-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_orderitem_paid_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='covered_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity covered by subscription or reward.'),
        ),
    ]
