# Generated by Django 6.0.6 on 2026-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_orderitem_covered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reward_paid_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of reward items that exceeded the reward limit.'),
        ),
    ]
