# Generated by Django 6.0.6 on 2026-06-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
