# Generated by Django 6.0.6 on 2026-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
