# Generated by Django 6.0.6 on 2026-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='default_pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
