# Generated by Django 6.0.6 on 2026-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_default_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
