# Generated by Django 6.0.6 on 2026-06-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_admin_seen',
            field=models.BooleanField(default=False),
        ),
    ]
