# Generated by Django 6.0.6 on 2026-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
