# Generated by Django 6.0.6 on 2026-07-30 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prize_type', models.CharField(choices=[('items_5', '5 Free Laundry Items'), ('items_10', '10 Free Laundry Items'), ('items_15', '15 Free Laundry Items'), ('items_30', '30 Free Laundry Items'), ('transport_1', 'Free Transport (1 Trip)'), ('transport_3', 'Free Transport (3 Trips)'), ('subscription_standard', 'Standard Subscription'), ('subscription_premium', 'Premium Subscription'), ('express', 'Express Service Upgrade'), ('try_again', 'Try Again')], max_length=30)),
                ('value', models.PositiveIntegerField(default=0, help_text='Number of items, trips or subscription duration.')),
                ('probability', models.PositiveIntegerField(default=1, help_text='Higher value means a greater chance of winning.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekendRewardCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_winners', models.PositiveIntegerField(default=5)),
                ('winners_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Closed', 'Closed')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_number', models.PositiveSmallIntegerField(default=1, help_text='Customer spin number for this campaign.')),
                ('has_won', models.BooleanField(default=False)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('reward_applied', models.BooleanField(default=False, help_text="Reward has been applied to customer's account.")),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_spins', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='rewards.rewardprize')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='rewards.weekendrewardcampaign')),
            ],
            options={
                'verbose_name': 'Spin History',
                'verbose_name_plural': 'Spin Histories',
                'ordering': ['-spun_at'],
            },
        ),
        migrations.AddField(
            model_name='rewardprize',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='rewards.weekendrewardcampaign'),
        ),
        migrations.CreateModel(
            name='RewardNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('bubble_seen', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.weekendrewardcampaign')),
            ],
            options={
                'unique_together': {('customer', 'campaign')},
            },
        ),
    ]
