# Generated by Django 6.0.6 on 2026-07-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('remaining_items', models.PositiveIntegerField(default=0)),
                ('free_transport_trips', models.PositiveIntegerField(default=0)),
                ('free_express_services', models.PositiveIntegerField(default=0)),
                ('subscription_days', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rewards', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rewards', to='rewards.rewardprize')),
                ('spin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reward', to='rewards.spinhistory')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
