# Generated by Django 6.0.6 on 2026-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_customerreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardprize',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
