# Generated by Django 6.0.6 on 2026-07-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewardprize_reward_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardprize',
            name='value',
        ),
    ]
