# Generated by Django 6.0.6 on 2026-07-31 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_remove_rewardprize_reward_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rewardprize',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_prizes', to='rewards.rewardpolicy'),
        ),
        migrations.CreateModel(
            name='RewardPolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Everyday Wear', 'Everyday Wear'), ('Corporate Wear', 'Corporate Wear'), ('Traditional Wear', 'Traditional Wear'), ('Underwear', 'Underwear'), ("Children's Wear", "Children's Wear"), ('Bedding', 'Bedding'), ('Shoes&Accessories', 'Shoes&Accessories'), ('Special Care', 'Special Care')], max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to='rewards.rewardpolicy')),
            ],
            options={
                'unique_together': {('policy', 'category')},
            },
        ),
        migrations.CreateModel(
            name='RewardPolicyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Wash & Fold', 'Wash & Fold'), ('Wash & Iron', 'Wash & Iron'), ('Dry Cleaning', 'Dry Cleaning')], max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_services', to='rewards.rewardpolicy')),
            ],
            options={
                'unique_together': {('policy', 'service_type')},
            },
        ),
    ]
