# Generated by Django 6.0.6 on 2026-07-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_rewardpolicy_rewardprize_policy_rewardpolicycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpolicy',
            name='apply_to',
            field=models.CharField(choices=[('ITEMS', 'Laundry Items'), ('TRANSPORT', 'Transport'), ('EXPRESS', 'Express Service'), ('SUBSCRIPTION', 'Subscription')], default='ITEMS', max_length=20),
        ),
    ]
