# Generated by Django 6.0.6 on 2026-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_rewardpolicy_apply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardprize',
            name='validity_days',
            field=models.PositiveIntegerField(default=14, help_text='Number of days the reward remains valid.'),
        ),
    ]
