# Generated by Django 6.0.6 on 2026-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_rewardprize_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekendrewardcampaign',
            name='max_spins_per_customer',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of spins each customer can use.'),
        ),
    ]
