# Generated by Django 6.0.6 on 2026-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0008_weekendrewardcampaign_max_spins_per_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreward',
            name='booking_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreward',
            name='is_booking_ready',
            field=models.BooleanField(default=False, help_text='Customer has prepared this reward for booking.'),
        ),

    ]
