# Generated by Django 6.0.6 on 2026-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_customerreward_booking_ready_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardprize',
            name='value',
            field=models.PositiveIntegerField(default=0, help_text='Number of items, trips or subscription duration.'),
        ),
    ]
